config/routes.rb
LaunchGator::Application.routes.draw do

  resources :contact_us,:only=>[:new,:create]

  match '/:id' => 'invites#referral', :constraints => {:id => /[a-zA-Z]{3}[0-9]{3}/}

  resources :invites,:only=>[:create] do
    member do
      get 'referral'
    end
  end

  resources :sites, :only=>[:index,:edit,:update]   do
    member do
      get 'view'
    end
    resources :invites,:only=>[:index]
  end

  devise_for :users, controllers: { omniauth_callbacks: "sessions" }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users, :only => [:index] do
    collection do
      get 'home'
    end

  end

  post 'check_user' => 'users#check_user', :as => :check_user
  get 'terms'=>'pages#terms',:as=>:terms
  get 'contact' => 'contact_us#new',:as=>:contact
  get 'about' => 'pages#about', :as => :about
  get 'terms'=>'pages#terms',:as=>:terms
  get 'privacy_policy'=>'pages#privacy_policy',:as=>:privacy_policy

  get 'check_domain_propagated' => 'sites#check_domain_propagated', :as=> :check_domain_propagated
  match 'auth/failure', to: redirect('/')

  root :to => 'users#home'

  constraints(Subdomain) do
    root :to => 'sites#view'
  end

end

app/views/notifier/account_activation_mail.html.erb
<table style="width: 600px;margin: 10px auto;padding: 0;border: none;border-spacing: 0;border-collapse: collapse;font-family:'Helvetica', 'arial', sans-serif;font-size:18px; color: #333;font-weight:300;" align="center">
	<tbody>
		<tr>
			<td style="background:#fff;border:1px solid #f5f5f5;border-bottom: 2px solid #c03;padding: 30px 20px;margin: 0;font-size: 24px;font-weight: 700;">
				<%= link_to root_path do %>
					<img src="http://launch.deskgator.com/assets/emailogo.png" width="210" height="50" alt="Launch Gator Logo">
				<% end %>
			</td>
		</tr>
		<tr>
			<td style="background:#fafafa;padding: 20px;margin: 0;border:1px solid #f5f5f5;">
				<h1 style="font-size: 18px;">Hi <%= @recipient.full_name %></h1>
				<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;">Your account has been created successfully, you just need to validate your email. To validate your email use the link below.</p>
				<%= url_for(activate_url(:code => @recipient.activation_code)), style: 'display: inline-block;padding: 10px 15px; background: #c03;text-decoration:none' %>
				<p style="font-size: 16px;color: #444;font-weight: 300;"><strong>Cheers!</strong><br>
					LaunchGator Team
				</p>
			</td>
		</tr>
		<tr>
			<td style="background:#f5f5f5;border: none;padding: 15px;margin: 0;border:1px solid #eee;">
				<p style="font-size: 12px;color: #666;font-weight: 300;"><strong>LaunchGator</strong> has sent this e-mail to you because it was necessary or you opted for this. If you dont want to receive these emails please let us know.</p>
			</td>
		</tr>
	</tbody>
</table>		

app/views/notifier/contact_us_mail_to_admin.html.erb
<body>
<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #f1f1f1;font-family: Arial, Helvetica, sans-serif">
  <tr>
    <th style="border-bottom:1px solid #ccc;border-right:1px solid #F1F1F1;width: 250px;height: 100px;" align="center"><img src="http://launch.deskgator.com/assets/emailogo.png" width="210" height="50" alt="Launch Gator Logo"></th>
    <th colspan="2"height="100" scope="col" style="border-bottom:1px solid #ccc;color:#666;">Create awesome launch pages!</th>

  </tr>
  <tr>
    <td colspan="2" style="padding:20px">
    <p style="font-size:14px">
     	<%= @contact_us.name  %> left a message
     <br/><br/>
     	Subject: <%= @contact_us.subject %>
     <br/><br/>
     	Comment: <%= @contact_us.comment %>
     <br/><br/>
     	Phone: <%= @contact_us.phone_number %>
      <br/><br/>
     	Email: <%= @contact_us.email %>
      <br/>
    </td>
  </tr>
  <tr>
    <td colspan="2" style="padding:20px;border-top:1px solid #ccc;font-size:12px;">
	<strong>P.S.</strong> - Please mark this email as not spam (unless our magic worked and it landed in your inbox) and add us to your contacts.</td>
  </tr>
</table>
</body>

app/views/notifier/daily_stats.html.erb
<table style="width: 600px;margin: 10px auto;padding: 0;border: none;border-spacing: 0;border-collapse: collapse;font-family:'Helvetica', 'arial', sans-serif;font-size:18px; color: #333;font-weight:300;" align="center">
  <tbody>
    <tr>
      <th style="border-bottom:1px solid #ccc;width: 250px;height: 100px;" align="center"><a href="http://launch.deskgator.com?utm_source=launchgator&utm_medium=email&utm_campaign=daily_email"><img src="http://launch.deskgator.com/assets/emailogo.png" width="210" height="50" alt="Launch Gator Logo"></a></th>
    </tr>
    <tr>
      <td style="background:#fafafa;padding: 20px;margin: 0;border:1px solid #f5f5f5;">
        <h1 style="font-size: 18px;">Hi,</h1>
        <p style="font-size: 18px;color: #444;line-height:24px;font-weight: 300;">New Signups on <%= @site.name if @site.name?%> for today!</p>
        <%@today_invites.pluck('email').each do |email| %>
        <span style="font-size: 14px;color: #666;line-height:20px;font-weight: 300;padding: 10px;margin:2px 2px 5px 0;background:#fff;display:inline-block;border-left:5px solid #c30"><%= email %></span>
        <% end %>
        <br>
        <p style="font-size: 16px;color: #444;font-weight: 300;"><strong>Cheers!</strong><br>
          The LaunchGator Team
        </p>
      </td>
    </tr>
    <tr>
      <td style="background:#f5f5f5;border: none;padding: 15px;margin: 0;border:1px solid #eee;">
        <p style="font-size: 12px;color: #666;font-weight: 300;">Please mark this email as not spam (unless our magic worked and it landed in your inbox) and add us to your contacts.</p>
        <%= link_to "Powered by LaunchGator", root_url, style: "font-size: 12px;font-weight: 700;color: #c03;text-decoration: none;display:inline-block;" %>
      </td>
    </tr>
  </tbody>
</table>

app/views/notifier/invite_mail_sent.html.erb
<table style="width: 600px;margin: 10px auto;padding: 0;border: none;border-spacing: 0;border-collapse: collapse;font-family:'Helvetica', 'arial', sans-serif;font-size:18px; color: #333;font-weight:300;" align="center">
	<tbody>
		<tr>
			<td style="background:#fff;border:1px solid #f5f5f5;border-bottom: 2px solid #c03;padding: 30px 20px;margin: 0;font-size: 24px;font-weight: 700;">
				<% if !@site.image.nil? and !@site.image.logo_file_name.nil? %>
				<%= link_to image_tag(root_url + @site.image.logo.url(:medium), :style=>"width:auto;height:50px;min-height:50px;max-height:50px"), @recipient.short_url %>
				<% elsif !@site.logo.nil? %>
				<h1 style="font-size:26px;margin: 0;">
					<%= link_to  @site.logo , @recipient.short_url, style: "text-decoration: none; color: #333" %>
				</h1>
				<% else %>
				<h1 style="font-size:26px;margin: 0;">
					<%= link_to  @site.logo , @recipient.short_url, style: "text-decoration: none; color: #333" %>
				</h1>
				<% end %>
			</td>
		</tr>
		<tr>
			<td style="background:#fafafa;padding: 20px;margin: 0;border:1px solid #f5f5f5;">
				<h1 style="font-size: 18px;">Hi,</h1>
				<% if @site.welcome_email.nil? %>
					<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;">Thank you for signing up!</p>
					<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;">Invite more friends via Facebook, Twitter or email to get early access (make sure to use your referral link: <%= @recipient.short_url %>).</p>
				<% else %>
					<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;">
					<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true) %>
					<% welcome_email = @site.welcome_email.gsub('%share_referral_link%',@recipient.short_url) %>
					<%= markdown.render(welcome_email).html_safe %></p>
				<% end %>
				<p style="font-size: 16px;color: #444;font-weight: 300;"><strong>Cheers!</strong><br>
					The <%= @site.name %> Team
				</p>
			</td>
		</tr>
		<tr>
			<td style="background:#f5f5f5;border: none;padding: 15px;margin: 0;border:1px solid #eee;">
				<p style="font-size: 12px;color: #666;font-weight: 300;">Please mark this email as not spam (unless our magic worked and it landed in your inbox) and add us to your contacts.</p>
				<%= link_to "Powered by LaunchGator", root_path, style: "font-size: 12px;font-weight: 700;color: #c03;text-decoration: none;display:inline-block;" %>
			</td>
		</tr>
	</tbody>
</table>

app/views/notifier/password_recovery.html.erb
<table style="width: 600px;margin: 10px auto;padding: 0;border: none;border-spacing: 0;border-collapse: collapse;font-family:'Helvetica', 'arial', sans-serif;font-size:18px; color: #333;font-weight:300;" align="center">
	<tbody>
		<tr>
			<td style="background:#fff;border:1px solid #f5f5f5;border-bottom: 2px solid #c03;padding: 30px 20px;margin: 0;font-size: 24px;font-weight: 700;">
				<%= link_to root_path do %>
					<img src="http://launch.deskgator.com/assets/emailogo.png" width="210" height="50" alt="Launch Gator Logo">
				<% end %>
			</td>
		</tr>
		<tr>
			<td style="background:#fafafa;padding: 20px;margin: 0;border:1px solid #f5f5f5;">
				<h1 style="font-size: 18px;">Hi <%= @recipient.full_name %></h1>
				<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;">Somebody requested to reset your password on LaunchGator. If it was you use the link below.</p>
				<%= url_for(password_url(:code=>@recipient.forgot_password_code)), style: 'display: inline-block;padding: 10px 15px; background: #c03;text-decoration:none' %>
				<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;">If you've received this mail in error, it's likely that another user entered your email address by mistake while trying to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely disregard this email.</p>
				<p style="font-size: 16px;color: #444;font-weight: 300;"><strong>Cheers!</strong><br>
					LaunchGator Team
				</p>
			</td>
		</tr>
		<tr>
			<td style="background:#f5f5f5;border: none;padding: 15px;margin: 0;border:1px solid #eee;">
				<p style="font-size: 12px;color: #666;font-weight: 300;"><strong>LaunchGator</strong> has sent this e-mail to you because it was necessary or you opted for this. If you dont want to receive these emails please let us know.</p>
			</td>
		</tr>
	</tbody>
</table>		

app/views/notifier/send_a_record_entry_notification_mail.html.erb
<body>
	<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #f1f1f1;font-family: Arial, Helvetica, sans-serif">
		<tr>
			<th style="border-bottom:1px solid #ccc;border-right:1px solid #F1F1F1;width: 250px;height: 100px;" align="center">
				<img src="http://launch.deskgator.com/images/emailogo.png" width="210" height="50" alt="Launch Gator Logo">
			</th>
			<th colspan="2"height="100" scope="col" style="border-bottom:1px solid #ccc;color:#666;">Create awesome launch pages!</th>
		</tr>
		<tr>
			<td colspan="2" style="padding:20px">
				<p style="font-size:14px">
					Hi <%= @recipient.full_name %>,
					<br/>
					<br/><br/>
					You need to follow the following simple steps to get your site up and running.<br/>
					Set Up Your A Records
					<br/><br/>
					Below are instructions for updating the A record for your domain.
					<br/><br/>
					Go to your registrar (or hosting provider if you have changed the nameservers to them), find your DNS settings and follow the instructions to point the A record (IP address) for your domain to the following IP address hosted by LaunchGator: 97.107.138.139.<br/>
					NOTE: You need to change your domain’s (or sub-domain’s) A record, not its nameservers. And, you don’t need to forward or redirect anything, you only need to change the A Record.<br/>
					Verify that your domain name is pointing to <a href="http://launch.deskgator.com">launch.deskgator.com</a> by typing it into your browser. Once the changes have propagated, it will redirect you to <a href="http://launch.deskgator.com">launch.deskgator.com</a> if the site has not been activated yet. If the site has been activated, then your domain should point to your 
					<a href="http://launch.deskgator.com">LaunchGator</a> page. (Depending on your registrar, it can take a while for the A record to propagate.)
					<br/><br/>
					Now What?
					<br/><br/>
					After you know your site is functioning properly, start spreading the word! We helps amplify your message, but if you don't bring some traffic to it, there is nothing to amplify. You've got some work to do!
					<br/><br/>
					Get your friends to sign up and share it, but more importantly start sending it to people and blogs you know would be interested. Some of our users have had amazing results simply sending tweets to people and blogs to check their site out.
					<br/><br/><br/><br/>
					<br/>
					Cheers!!
					<br/>
					LaunchGator Team
				</p>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="padding:20px;border-top:1px solid #ccc;font-size:12px;">
				<strong>P.S.</strong> - Please mark this email as not spam (unless our magic worked and it landed in your inbox) and add us to your contacts.
			</td>
		</tr>
	</table>
</body>

app/views/notifier/send_daily_report_mail.html.erb
<body>
	<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #f1f1f1;font-family: Arial, Helvetica, sans-serif">
		<tr>

			<th style="border-bottom:1px solid #ccc;border-right:1px solid #F1F1F1;width: 250px;height: 100px;" align="center">
				<p align="center">
					<% if !@site.image.nil? and !@site.image.logo_file_name.nil? %>
						<%= image_tag(root_url + @site.image.logo.url(:medium), :style=>"width:220px;height:auto;") %>
					<% elsif !@site.logo.nil? %>
					<h1 style="color:<%= @site.name_color %>!important">
						<%= @site.logo  %>
					</h1>
					<% else %>
					<h1 style="color:<%= @site.name_color %>!important">
						<%= @site.name %>
					</h1>
					<% end %>
				</p>
			</th>
			<th colspan="2"height="100" scope="col" style="border-bottom:1px solid #ccc;color:#666;">
				<%= @site.tagline %>
			</th>

		</tr>
		<tr>

			<td colspan="2" style="padding:20px">
				<div style="text-align:center">
				Activity on your landing page for <strong><%= @daily_report.created_at.to_date %></strong>
				<br>
				<br>
				<span style="font-size:26px;font-weight:700">Visits</span>&nbsp;
				<span style="font-size:26px;font-weight:400"><%= @daily_report.views_count %></span>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<span style="font-size:26px;font-weight:700">SignUp's</span>&nbsp;
				<span style="font-size:26px;font-weight:400"><%= @daily_report.signups_count %></span>
				<br/>
				<br/>
			    <br/>
			</div>

			      Cheers!!
			     <br/>
			      LaunchGator Team
			</td>

		</tr>
		<tr>
			<td colspan="2" style="padding:20px;border-top:1px solid #ccc;font-size:12px;">
				<strong>P.S.</strong> - Please mark this email as not spam (unless our magic worked and it landed in your inbox) and add us to your contacts.<br/>
			</td>
		</tr>
	</table>
</body>

app/views/notifier/we_are_missing_you.html.erb
<h1 style="font-size: 18px;">Hi <%= @recipient.full_name %>,</h1>
<p style="font-size: 14px;color: #444;font-weight: 300;line-height: 18px;margin-bottom: 10px;">
	We have missed you :(
</p>
<p style="font-size: 14px;color: #444;font-weight: 300;line-height: 18px;margin-bottom: 10px;">
This is to remind you that you have been missing out the fun.
</p>

app/views/notifier/welcome.html.erb
<table style="width: 600px;margin: 10px auto;padding: 0;border: none;border-spacing: 0;border-collapse: collapse;font-family:'Helvetica', 'arial', sans-serif;font-size:18px; color: #333;font-weight:300;" align="center">
	<tbody>
		<tr>
			<td style="background:#fff;border:1px solid #f5f5f5;border-bottom: 2px solid #c03;padding: 30px 20px;margin: 0;font-size: 24px;font-weight: 700;">
				<%= link_to root_url do %>
				<img src="http://launch.deskgator.com/assets/emailogo.png" width="210" height="50" alt="Launch Gator Logo">
				<% end %>
			</td>
		</tr>
		<tr>
			<td style="background:#fafafa;padding: 20px;margin: 0;border:1px solid #f5f5f5;">
				<h1 style="font-size: 18px;">Hi <%= @recipient.full_name %></h1>
				<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;">Your account has been created, please go ahead and create a viral launching soon page for your website.</p>
				<p style="font-size: 16px;color: #444;line-height:24px;font-weight: 300;"><% unless @random_password.blank? %>
				Your Password is <strong><%= @random_password %></strong><br/>
				Please change your password when you login!
				<% end %>
				</p>
				<%= link_to "View Account", root_path, style: 'display: inline-block;padding: 10px 15px; background: #c03;text-decoration:none; font-weight:700;color: #fff' %>
				<p style="font-size: 16px;color: #444;font-weight: 300;"><strong>Cheers!</strong><br>
					LaunchGator Team
				</p>
			</td>
		</tr>
		<tr>
			<td style="background:#f5f5f5;border: none;padding: 15px;margin: 0;border:1px solid #eee;">
				<p style="font-size: 12px;color: #666;font-weight: 300;"><strong>LaunchGator</strong> has sent this e-mail to you because it was necessary or you opted for this. If you dont want to receive these emails please let us know.</p>
			</td>
		</tr>
	</tbody>
</table>