config/routes.rb
LaunchGator::Application.routes.draw do

  resources :contact_us,:only=>[:new,:create]

  match '/:id' => 'invites#referral', :constraints => {:id => /[a-zA-Z]{3}[0-9]{3}/}

  resources :invites,:only=>[:create] do
    member do
      get 'referral'
    end
  end

  resources :sites, :only=>[:index,:edit,:update]   do
    member do
      get 'view'
    end
    resources :invites,:only=>[:index]
  end

  devise_for :users, controllers: { omniauth_callbacks: "sessions" }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users, :only => [:index] do
    collection do
      get 'home'
    end

  end

  post 'check_user' => 'users#check_user', :as => :check_user
  get 'terms'=>'pages#terms',:as=>:terms
  get 'contact' => 'contact_us#new',:as=>:contact
  get 'about' => 'pages#about', :as => :about
  get 'terms'=>'pages#terms',:as=>:terms
  get 'privacy_policy'=>'pages#privacy_policy',:as=>:privacy_policy

  get 'check_domain_propagated' => 'sites#check_domain_propagated', :as=> :check_domain_propagated
  match 'auth/failure', to: redirect('/')

  root :to => 'users#home'

  constraints(Subdomain) do
    root :to => 'sites#view'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :full_name,:account_type

  validates_presence_of :full_name, :email
  validates :email, :email_format => true

  has_one :site , :dependent => :destroy

  after_create :welcome_mail
  after_create :create_website , :unless => lambda{ |a| a.account_type == 'super_admin' }

  def welcome_mail
    Notifier.welcome(self).deliver
  end

  def create_website
    #site_url = 'http://' + self.full_name.delete(" ").to_s + ".com"
    site = Site.new
    site.user_id = self.id
    site.email = self.email

    site.sharing_instructions = "Invite at least 3 friends using the link below. The more friends you invite, the sooner you'll get access!<br>To share with your friends, click 'Recommend' or 'Tweet'"

    site.email_sender = self.email
    site.email_subject = 'Welcome to LaunchGator'
    site.welcome_email = "Thanks for signing up!     \r\n\r\nInvite more friends via Facebook, Twitter or email to get early access by sharing your unique link %share_referral_link%."
    site.url = "http://"
    site.save(:validate=>false)
  end

  def self.random_string
    #generate a random password consisting of strings and digits
    # chars = ("a".."z").to_a + ("A".."Z").to_a #+ ("0".."9").to_a
    # newpass = ""
    # 1.upto(10) { |i| newpass << chars[rand(chars.size-1)] }
    # return newpass
    [*'a'..'z', *'A'..'Z'].sample(3).join + (0..9).to_a.sample(3).join
  end


end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  full_name              :string(255)
#  oauth_token            :string(255)
#  oauth_expires_at       :datetime
#  uid                    :string(255)
#  provider               :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  authentication_token   :string(255)
#  username               :string(255)
#  account_type           :string(255)      default("user")
#  active                 :integer
#

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_filter :super_admin_acces, :only=>[:index]

    def index
        @users = User.paginate(:page => params[:page], :per_page=> 50)
    end

    def check_user
        @user = User.find_by_email(params[:user][:email])
        session[:checked_email] = params[:user][:email]
        if @user.present?
            redirect_to new_user_session_path
        else
            redirect_to new_user_registration_path
        end
    end

    def home
        if user_signed_in?
            @user = current_user
            @site = @user.site
            redirect_to edit_site_path(@site)
        else
            @site.update_attribute(:clicks, @site.clicks+1)
        end
   end

end

app/views/users/home.html.erb
<% if @site.id != 1 %>
	<%= render 'sites/view' %>
<% else %>
<div id="welcome_form" class="">
	<h1>
		<span class="launching">
			Create a Viral Launching Soon page
		</span>
		<span class="orange">
			in minutes for FREE!
		</span>
	</h1>
	<p align="center">
		Enter your email address to get started
	</p>
	<p id="error_message" align="center" style="display:none">

	</p>
	<div class="clear" id="form">
		<%= form_for @user, :as => :user , :url => check_user_path do |f| %>
			<%= f.text_field :email ,:class=>"txt_small home_email", :placeholder=>'yourname@yourmail.com' %>
			 <%= hidden_field_tag 'home_page', 'home_page' %>
			<%= submit_tag "Go" ,:class => "greenbutton" %>
		<% end %>
	</div>
	<%= hidden_field_tag 'site', @site.id %>
</p>
</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
	var initialText = "yourname@yourmail.com";
	$('#invite_email').focus(function(){
		if( $(this).val()==initialText){
			$(this).val("");
		}
	});
	$('#invite_email').blur(function(){
		if($(this).val()==""){
			$(this).val(initialText);
		}
	});
});


$('#notify_me').click(function() {
	$(".error").hide();
	var hasError = false;
	var emailReg = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
	var emailaddressVal = $("#invite_email").val();
	if(emailaddressVal == '') {
		$("#error_message").fadeIn();
		$("#error_message").html('Please enter your email address.');
		hasError = true;
	}

	else if(!emailReg.test(emailaddressVal) || emailaddressVal == 'yourname@yourmail.com') {
		$("#error_message").fadeIn();
		$("#error_message").html('Enter a valid email address.');
		hasError = true;
	}

	if (!hasError) {
		submit_email();
	}
	return false;

});
function submit_email()
{
	$.post("/invites", { email: $('#invite_email').val() , site_id: $('#site').val() ,referral_code: $('#referral_code').val()
}, function(response){
	$('#welcome_form').hide();
	$('#social_networks').show();
	$("#unique_code").show();
	$('#unique_code_textbox').val(response);
	$("meta[property=og\\:url]").attr("content",response);
});
}

$('#invite_email').keydown(function(e) {
	if (e.keyCode == 13) {
		$('#notify_me').click();
	}

});
</script>
<% end %>

app/views/users/index.html.erb
<h4 class="statslist">	
Listing <span class="stat">USERS</span>
</h4> 
<div class="divider"></div>

<table id="hor-minimalist-b">
	<thead>
		<th scope = "col">Full name</th>
		<th scope = "col">Account type</th>
		<th scope = "col">Email</th>
	</thead>

	<% @users.each do |user| %>
	<tr>
		<td><%= user.full_name %></td>
		<td><%= user.account_type %></td>
		<td><%= user.email %></td>
	</tr>
	<% end %>
</table>
<div><%= will_paginate @users  %></div>