config/routes.rb
LaunchGator::Application.routes.draw do

  resources :contact_us,:only=>[:new,:create]

  match '/:id' => 'invites#referral', :constraints => {:id => /[a-zA-Z]{3}[0-9]{3}/}

  resources :invites,:only=>[:create] do
    member do
      get 'referral'
    end
  end

  resources :sites, :only=>[:index,:edit,:update]   do
    member do
      get 'view'
    end
    resources :invites,:only=>[:index]
  end

  devise_for :users, controllers: { omniauth_callbacks: "sessions" }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users, :only => [:index] do
    collection do
      get 'home'
    end

  end

  post 'check_user' => 'users#check_user', :as => :check_user
  get 'terms'=>'pages#terms',:as=>:terms
  get 'contact' => 'contact_us#new',:as=>:contact
  get 'about' => 'pages#about', :as => :about
  get 'terms'=>'pages#terms',:as=>:terms
  get 'privacy_policy'=>'pages#privacy_policy',:as=>:privacy_policy

  get 'check_domain_propagated' => 'sites#check_domain_propagated', :as=> :check_domain_propagated
  match 'auth/failure', to: redirect('/')

  root :to => 'users#home'

  constraints(Subdomain) do
    root :to => 'sites#view'
  end

end

app/models/site.rb
require 'domainatrix'
class Site < ActiveRecord::Base
  attr_accessible :name, :url,:tagline, :description, :twitter, :facebook, :blog, :twitter_message, :google_analytics_code, :welcome_email, :email, :domain_name, :logo, :box_alignment, :box_visibility, :sharing_instructions, :email_subject, :business_name, :email_sender, :email_sender_name, :box_color, :name_color, :tagline_color, :description_color, :address,:image_attributes, :site_urls_attributes, :user_id, :domain_propagated, :state

  has_one :image, :dependent => :destroy
  belongs_to :user
  has_many :invites, :dependent => :destroy
  has_many :site_urls, :dependent => :destroy
  has_many :daily_reports, :dependent => :destroy

  accepts_nested_attributes_for :image,:allow_destroy => true
  accepts_nested_attributes_for :site_urls, reject_if: :check_url_blank?, :allow_destroy => true
  validates_presence_of :name, :url, :tagline, :email, :description
  validates :name, :url, :uniqueness => true, :allow_blank => true
  validates :email, :email_format => true

   validates_format_of :url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix,
   :unless => lambda{|a| a.url.blank?}

   before_save :update_email_subject
   before_update :update_state_of_status_bar

  def self.find_site_from_orignal_url(original_url)
    @url_params = Domainatrix.parse(original_url)
    @original_url = @url_params.scheme + "://" + @url_params.host
    site = find_by_url(@original_url)
    site = SiteUrl.find_site_by_url(@original_url) if site.blank?
    if site.blank?
      raise ActiveRecord::RecordNotFound.new
    else
      return site
    end
  end


  def parse_domain_name_from_url
    url = Domainatrix.parse(self.url)
    self.domain_name = url.domain
    self.save
  end

  def update_email_subject
    if self.email_subject_changed?
      self.email_subject = self.email_subject
    elsif self.name_changed? and !self.email_subject_changed?
      if self.email_subject_was == "Welcome To #{self.name_was}" or self.email_subject_was == "Welcome to LaunchGator"
        self.email_subject = "Welcome To #{self.name}"
      else
        self.email_subject = self.email_subject
      end
    end
  end

  def domain_mapped?
    check_url = url if !url.nil?
    `curl -I "#{check_url}"`.match('_launch_gator_session').present?
  end

  def check_url_blank?(site_urls_attributes)
    if site_urls_attributes[:url].blank?
      return true
    end
  end

  def update_state_of_status_bar
    if self.url_changed? and self.image.present?
        self.state = 2
        self.domain_propagated = 0
    elsif self.image != nil and self.domain_propagated != true
        self.state =  2
        self.domain_propagated = 0
    elsif self.url_changed?
        self.state = 1
    elsif self.url.present? and self.image != nil and self.domain_propagated != true
        self.stage = 2
    elsif self.url.present? and self.domain_propagated != true and self.image == nil
      self.state = 1
    end
  end

  def self.daily_stats
    time_range = (Time.now.midnight - 1.day)..Time.now.midnight
    @site = self.joins(:invites).where('invites.created_at' => time_range).uniq
    @site.each do |site|
    @today_invites = site.invites.where(:created_at => time_range)
    Notifier.daily_stats(@today_invites, site).deliver
    end
  end


end

# == Schema Information
#
# Table name: sites
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  user_id               :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  url                   :string(255)
#  tagline               :string(255)
#  description           :text
#  twitter               :string(255)
#  facebook              :string(255)
#  blog                  :string(255)
#  twitter_message       :string(255)
#  google_analytics_code :text
#  welcome_email         :text
#  email                 :string(255)
#  domain_name           :string(255)
#  clicks                :integer          default(0)
#  logo                  :string(255)
#  box_alignment         :string(255)
#  box_visibility        :string(255)
#  sharing_instructions  :text
#  email_subject         :text
#  business_name         :string(255)
#  email_sender          :string(255)
#  email_sender_name     :string(255)
#  box_color             :string(255)      default("total_black")
#  name_color            :string(255)      default("#ffffff")
#  tagline_color         :string(255)      default("#ffffff")
#  description_color     :string(255)      default("#ffffff")
#  address               :string(255)
#  domain_propagated     :boolean          default(FALSE)
#  state                 :integer          default(0)
#

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authorize, :only=>[:edit, :update]
  before_filter :super_admin_acces, :only=>[:index]
  before_filter :validate_subdomain, :only=>[:view]
  before_filter :sterilize_url, :only => [:update, :create]

  def index
    @sites = Site.paginate(:page => params[:page], :per_page=> 50)
  end

  def edit
    @site.build_image if @site.image.nil?
    if params[:tab]
      @active_tab = params[:tab].split(" ")
      @active_tab = @active_tab[0]
    end
    @active_tab
  end

  def update
    if @site.update_attributes(params[:site])
      if !@site.image.nil?
        @site.image.update_colums(params)
      end
      @site.parse_domain_name_from_url
      flash[:notice] = "Site was successfully updated."
      redirect_to(edit_site_path(@site))
    else
      @site.build_image if @site.image.nil?
      render :action => "edit"
    end
  end

  def view
    @site.update_attribute(:clicks, @site.clicks+1)
    @visited = site_visited_or_not(@site.id)
    @invite = Invite.new
  end

  def check_domain_propagated
    @site = current_user.site if current_user.present?
    if @site.domain_mapped? == true
      @site.update_attributes(:domain_propagated => 1, :state => 3)
      redirect_to edit_site_path(@site), notice: "congratulations Your site is working now start sharing it and collect signup."
    else
      @site.update_attribute(:domain_propagated, 0)
      redirect_to edit_site_path(@site), :flash => {:error => "Please check your cname setting is it pointing to host.deskgator.com"}
    end
  end

  private

  def authorize
    begin
      @site = Site.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "This record does not exist."
      redirect_to(root_path)
    else
      unless current_user.present? and @site.user_id == current_user.id
        flash[:error] = "You are not authorized for this."
        redirect_to(root_path)
      end

    end
  end

  def no_delete_for_default_site
    if params[:id]==1
      redirect_to(root_path)
    end
  end

  def validate_subdomain
    if request.subdomain.to_s  != "launch"
      subdomain = request.subdomain.to_s.gsub('.launch','')
      begin
        @site = Site.find_by_domain_name!(subdomain)
      rescue ActiveRecord::RecordNotFound
        flash[:error] = "This record does not exist."
        redirect_to(root_path(:subdomain=>false))
      end
    else
      @site = Site.find(1)
    end
  end

  def sterilize_url
    params[:site][:url] = params[:site][:url].chop  if params[:site][:url].last == "/"
  end

end

app/views/sites/_form.html.erb
<div id="site_wrapper"  style="background-color:<%= @site.box_color %>!important">
	<%= render 'site_view' %>
</div>
<div id="site_builder">
	<h1>Site Builder<span id="close_modal">x</span></h1>
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1" class="tabs-1">Basics</a></li>
			<li><a href="#tabs-2" class="tabs-2">Images</a></li>
			<li><a href="#tabs-3" class="tabs-3">Sharing</a></li>
			<li><a href="#tabs-6" class="tabs-6">Email</a></li>
			<li><a href="#tabs-7" class="tabs-7">Colors</a></li>
			<li><a href="#tabs-5" class="tabs-5">Domain</a></li>
			<li><a href="#tabs-4" class="tabs-4">Optional</a></li>
		</ul>
		<%= form_for @site, :html => { :multipart => true } do |f| %>
		<% if @site.errors.any? %>
		<div id="error_explanation">
			<h2>The following errors occurred. Please try again:</h2>
			<ul>
				<% @site.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div id="tabs-1"><%= render 'tabs_1', :f => f %></div>
		<div id="tabs-2"><%= render 'tabs_2', :f => f %></div>
		<div id="tabs-3"><%= render 'tabs_3', :f => f %></div>
		<div id="tabs-6"><%= render 'tabs_6', :f => f %></div>
		<div id="tabs-7"><%= render 'tabs_7', :f => f %></div>
		<div id="tabs-5"><%= render 'tabs_5', :f => f %></div>
		<div id="tabs-4"><%= render 'tabs_4', :f => f %></div>

		<p>
			<%= f.submit "Update",:class=>"greenbutton submitsite" %>
		</p>
		<% end  %>
	</div>
</div>

<script>
	$(function() {

		$("#tabs").tabs();

		$( "#site_description_color , #site_tagline_color, #site_name_color, #site_box_color").focus(function(){
			$('.' + this.id).show();
			$('.' + this.id).farbtastic(this);
		});

		$( "#site_description_color , #site_tagline_color, #site_name_color, #site_box_color").blur(function(){
			$('.' + this.id).hide();
		});
		$( "#close_modal").live('click',function(){
			$('#site_builder').hide();
		});
		$( "#open_modal").click(function(){
			$('#site_builder').show();
		});

	});
</script>

app/views/sites/_site_url_fields.html.erb
<fieldset class=<%= active_or_inactive_domain(f.object) %>>
  <%= f.label :url, "URL" %>
  <%= f.text_field :url %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "X", "#", class: "remove_fields" %>
</fieldset>

app/views/sites/_site_view.html.erb
<p align="center">
	<% if !@site.image.id.nil? and !@site.image.logo_file_name.nil? %>
	<%= link_to image_tag(@site.image.logo.url(:medium)), root_url %>
	<% elsif !@site.logo.nil? %>
	<h1 class="largeheader" style="color:<%= @site.name_color %>!important">
		<%=  @site.logo  %>
	</h1>
	<% else %>
	<h1 class="largeheader" style="color:<%= @site.name_color %>!important">
		<%=  @site.name  %>
	</h1>
	<% end %>

	<p class="tagline" style="color:<%= @site.tagline_color %>!important">
		<%= @site.tagline %>
	</p>

</p>

<div id="welcome_form" >
	<p class="site_description" style="color:<%= @site.description_color %>!important">
		<%= @site.description %>
	</p>
	<p align="center" class="punchline" style="color:<%= @site.description_color %>">
		Coming Soon! Enter your email to join our invite list.
	</p>
	<div class="clear" id="form">
		<input type="text" name="email" id="invite_email" placeholder="yourname@yourmail.com "/>
		<%= link_to "Go",  "#",:class=>"greenbutton topmarginfix" %>
	</div>
	<p style="float:right; margin-top:5px;">
		<span style="font-size:12px;font-weight: 700;color:<%= @site.description_color %>">
			Powered by
		</span>
		<a href="http://launch.deskgator.com">
			<img src="/assets/powered_logo.png" style="position: relative;top: 5px;margin-right: 6px;" alt="" />
		</a>
	</p>
</div>

<div id="social_networks" style="margin-top:20px;" class="<%= 'hide' if @visited.nil? %>">
	<%  if @visited.nil? %>
	<p>
		<h1 class="header_text patternhead" style="font-size: 16px;">
			Thanks! Want to get an early invitation?
		</h1>
	</p>
	<% else %>
	<div>
		<%= @visited.sharing_instructions %>
	</div>
	<div>
		<h1 class="header_text">
			Welcome Back!
		</h1>
		<div class="stats">
			<strong>
				Live Stats
			</strong>
			<%= @visited.views_count %> Views,
			<%= @visited.invites_count %> Signups
		</div>
	</div>
	<% end %>
	<div class="sharing_description">
		<%= @site.sharing_instructions %>
	</div>
	<br/>
	<br/>
	<div>
		<p style="font-size: 15px;text-align: center;">To share with your friends, click 'Recommend' and 'Tweet':</p>
		<div id="twitter-like" class="clear" style="width:150px;float:left;margin-left:50px;margin-top:20px;">
			<a href="http://twitter.com/share" class="twitter-share-button" data-url="<%= @site.url %>" data-text="<%= @site.twitter_message %>" data-count="horizontal" data-via="<%= @site.twitter %>">Tweet</a>
			<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
		</div>

		<div id="facebook-like" style="margin-top:20px;">
			<iframe src="http://www.facebook.com/plugins/like.php?href=<%= @site.url %>&amp;layout=standard&amp;show_faces=false&amp;width=450&amp;action=recommend&amp;font=arial&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden;  width:95px; height:30px;" allowTransparency="true"></iframe>
		</div>
	</div>

	<div class="<%= 'hide' if @visited.nil? %>" id='unique_code' style="margin-top:5px;">
		<br/>
		<span>Or copy and paste the following link to share wherever you want!</span>
		<br/><br/>
	</div>
	<div>
		<input type="text" id="unique_code_textbox" class="home_page_text_box_1" value="<%= @site.url %>"/>
	</div>
</div>



<script type="text/javascript" charset="utf-8">
$(document).ready(function(){

});

$('.greenbutton').click(function() {
	$('#welcome_form').hide();
	$('#social_networks').show();
	$("#unique_code").show();
	$('#unique_code_textbox').val(response);
});

$('#invite_email').keydown(function(e) {
	if (e.keyCode == 13) {
		$('#notify_me').click();
	}
});
</script>

app/views/sites/_tabs_1.html.erb
<p>
  <%= f.label :name %>
</p>
<p>
  <%= f.text_field :name,  :class=>"txt_small" %>
</p>

<p>
  <%= f.label :tagline %>
</p>
<p> <%= f.text_field :tagline ,  :class=>"txt_small" %>
  <span class="hint_1">What makes your site exciting? </span>
</p>
<p>
  <%= f.label :description %>
</p>
<p><%= f.text_area :description %>
  <span class="hint_1"> More about the site, sometimes less is more.</span>
</p>

<p>
  <%= f.label :email %>
</p>
<p><%= f.text_field :email ,  :class=>"txt_small" %>
  <span class="hint_1">Contact mail will be sent here </span>
</p>

app/views/sites/_tabs_2.html.erb
<%= f.fields_for :image do |a_d| %>
<p>
	<label>Logo</label>

</p>

<% if !a_d.object.nil? and !a_d.object.logo_file_name.nil? %>
<input type="radio" name="logo" id="logo_image" checked><label for="logo_image" class="radiolabels">Image</label>
<input type="radio" name="logo" id="logo_text"><label for="logo_text" class="radiolabels">Text</label>
<span class="hint_1" style="margin-top:7px;" >
	<strong style="font-weight:700;color:#333">Current Logo</strong> : <%= a_d.object.logo_file_name %>
</span>   
<div class="logo_image">
	<p><%= a_d.file_field :logo,  :class=>"txt_small" %>
		<input name="logo_destroy" id="logo_destroy" type="checkbox" style="display:none">	    
		<span class="hint_1">Company Logo. </span>
	</p>
</div>
<div class="logo_text" style="display:none;">
	<p><%= f.text_field :logo,  :class=>"txt_small" %>
		<span class="hint_1">Company Logo in text. </span>
	</p>
</div> 
<% else %>
<input type="radio" name="logo" id="logo_image" ><label for="logo_image" class="radiolabels">Image</label>   
<input type="radio" name="logo" id="logo_text" checked><label for="logo_text" class="radiolabels">Text</label>
<div class="logo_image" style="display:none;">
	<p><%= a_d.file_field :logo,  :class=>"txt_small" %>
		<input name="logo_destroy" id="logo_destroy" type="checkbox" style="display:none">	    
		<span class="hint_1">Company Logo. </span>
	</p>
</div>
<div class="logo_text" >
	<p><%= f.text_field :logo,  :class=>"txt_small" %>
		<span class="hint_1">Company Logo in text. </span>
	</p>
</div>
<% end %>  



<% if !a_d.object.nil? and !a_d.object.background_file_name.nil? %> 
<p>
	<%= a_d.label :background , "Background Image"%>
	<input type="radio" name="background" id="background_default"><label for="background_default"  class="radiolabels">Default</label>   
	<input type="radio" name="background" id="background_custom" checked><label for="background_custom" class="radiolabels">Custom</label>
	<span class="hint_1" style="margin-top:7px;" >
		<strong style="font-weight:700;color:#333">Current Background</strong> : <%= a_d.object.background_file_name %>
	</span>
</p>
<p class="background_fields">
	<%= a_d.file_field :background,  :class=>"txt_small" %>
	<input name="background_destroy" id="background_destroy" type="checkbox" style="display:none">	    
	<span class="hint_1">Background.</span>
</p> 
<% else %>
<p>
	<%= a_d.label :background , "Background Image"%>
	<input type="radio" name="background" id="background_default" checked><label for="background_default"  class="radiolabels">Default</label>   
	<input type="radio" name="background" id="background_custom"><label for="background_custom" class="radiolabels">Custom</label>
	<span class="hint_1" style="margin-top:7px;" >
		<strong style="font-weight:700;color:#333">Current Background</strong> : <%= a_d.object.background_file_name %>
	</span>
</p>
<p class="background_fields" syle="display:none">
	<%= a_d.file_field :background,  :class=>"txt_small" %>
	<input name="background_destroy" id="background_destroy" type="checkbox" style="display:none">	    
	<span class="hint_1">Background.</span>
</p>
<% end%>

<% end %>
<p>
<%= f.label :box_alignment , "Box Alignment"%>
</p>
<p>
	<% site_box_alignment = {'Center'=>'center','Top-Left'=>'topleft','Top-Right'=>'topright','Bottom-Left'=>'bottomleft','Bottom-Right'=>'bottomright'} %>
	<%= f.select :box_alignment, site_box_alignment %>
	<span class="hint_1"> Where you want to place your site block?</span>
</p>

<script>
$(function() {
	$( "#logo_image").live('click',function(){
		$('.logo_image').show();
		$('.logo_text').hide();
		$('#logo_destroy').attr('checked',false);
	});
	$( "#logo_text").live('click',function(){
		$('.logo_text').show();
		$('.logo_image').hide();
		$('#logo_destroy').attr('checked',true);
	}); 
	$( "#background_custom").live('click',function(){
		$('.background_fields').show();
		$('#background_destroy').attr('checked',false);
	});
	$( "#background_default").live('click',function(){
		$('.background_fields').hide();
		$('#background_destroy').attr('checked',true);
	});
});
</script>

app/views/sites/_tabs_3.html.erb
<p>
	<%= f.label :twitter %>
</p>
<p><%= f.text_field :twitter ,  :class=>"txt_small" %>
	<span class="hint_1">e.g. myTwitter (no @ sign) </span>
</p>
<p>
	<%= f.label :twitter_message %>
</p>	
<p> <%= f.text_field :twitter_message ,  :class=>"txt_small" %>
	<span class="hint_1">The suggested tweet. </span>
</p>
<p>
	<%= f.label :facebook %>
</p>
<p> <%= f.text_field :facebook ,  :class=>"txt_small" %>
	<span class="hint_1">e.g. facebook.com/myFacebook (optional) </span>
</p>
<p>
	<%= f.label :blog %>
</p>
<p><%= f.text_field :blog ,  :class=>"txt_small" %>
	<span class="hint_1">The link to your blog (optional) </span>
</p>

<p>
	<%= f.label :sharing_instructions %>
</p>
<p>
	<%= f.text_area :sharing_instructions ,  :class=>"txt_small" %>
	<span class="hint_1">Sharing instructions for users</span>
</p>

app/views/sites/_tabs_4.html.erb
<p>
  <%= f.label :google_analytics_tracking_id %>
</p>
<p>
  <%= f.text_area :google_analytics_code ,  :class=>"txt_small", :placeholder=>"UA-XXXXXXXX-X" %>
  <span class="hint_1"> Google Analytics code</span>
</p>
<p>
  <%= f.label :address %>
</p>
<p>
  <%= f.text_area :address ,  :class=>"txt_small" %>
  <span class="hint_1">Business address for SPAM compliance</span>
</p>

app/views/sites/_tabs_5.html.erb
<p><%= f.label :url , "Primary URL" %></p>
  <p><%= f.text_field :url ,  :class=>"txt_small" %><span class="hint_1">The URL with a subdomain for your page, i.e. http://signup.mydomain.com. </span></p>

<ul class="integtype">
  <li id="arecord" class="active">A Record</li>
  <li id="cname">CNAME Record</li>
  <li id="other">Secondary Domain</li>
</ul>

<div id="arecord_tab">
  <h2>Set Up Your A Records</h2>
  <p>Below are instructions for updating the A Record for your domain.</p>
  <ul class="simplelist">
    <li>Go to your registrar (or hosting provider if you have changed the nameservers to them).</li>
    <li>Find your DNS settings</li>
    <li>Follow the instructions to point the A Record for your domain.</li>
    <li>Point the A Record to <strong> 198.211.117.169</strong> IP Address.</li>
    <li>Propagation of domain may take upto<strong> 24 - 48</strong> hours.</li>
  </ul>
  <em><strong>NOTE:</strong> You need to change your domain’s A Record, not its nameservers. And, you don’t need to forward or redirect anything, you only need to change the A Record.</em>
  <div class="domainstatus">
    <h6>Domain Status</h6>
    <% if @site.domain_propagated == true %>
    <h6 class="success">Propagated Successfully</h6>
    <% else %>
    <h6 class="failed">Propagation Pending</h6>
    <% end %>
    <%= link_to 'Test', check_domain_propagated_path, class: "checkstatus" %>
  </div>
</div>

<div id="cname_tab" class="hide">
  <h2>Set Up Your CNAME Record</h2>
  <p>Below are instructions for updating the CNAME record for your domain.</p>
  <ul class="simplelist">
    <li>Go to your registrar (or hosting provider if you have changed the nameservers to them).</li>
    <li>Find your DNS settings</li>
    <li>Follow the instructions to point the CNAME record (sub-domain) for your domain.</li>
    <li>Point the desired subdomain to <strong> host.deskgator.com</strong></li>
    <li>Propagation of subdomain may take upto<strong> 24 - 48</strong> hours.</li>
  </ul>
  <em><strong>NOTE:</strong> You need to change your domain’s (or sub-domain’s) CNAME record, not its nameservers. And, you don’t need to forward or redirect anything, you only need to change the CNAME Record.</em>
  <div class="domainstatus">
    <h6>Domain Status</h6>
    <% if @site.domain_propagated == true %>
    <h6 class="success">Propagated Successfully</h6>
    <% else %>
    <h6 class="failed">Propagation Pending</h6>
    <% end %>
    <%= link_to 'Test', check_domain_propagated_path, class: "checkstatus" %>
  </div>
</div>

<div id="other_tab" class="hide">
  <h2>Set Up Secondary URL's</h2>
  <p>This option lets you point other domains/url's to your launchgator page.</p>

  <div class="suburls">
    <%= f.fields_for :site_urls do |builder| %>
    <%= render "site_url_fields", :f => builder %>
    <% end %>
    <p class="addbtn" ><%= link_to_add_fields "Add Secondary URL", f, :site_urls%></p>
  </div>

</div>

<h3>Now What?</h3>
<p>After you know your site is functioning properly, start spreading the word! We helps amplify your message, but if you don't bring some traffic to it, there is nothing to amplify. You've got some work to do!</p>
<p>Get your friends to sign up and share it, but more importantly start sending it to people and blogs you know would be interested. Some of our users have had amazing results simply sending tweets to people and blogs to check their site out.</p>
<br>

app/views/sites/_tabs_6.html.erb
<p>
	<%= f.label :email_sender_name , "Sender name" %>
</p>
<p>
	<%= f.text_field :email_sender_name ,  :class=>"txt_small" %>
	<span class="hint_1">Send email as </span>
</p>

<p>
	<%= f.label :email_sender , "Sender email address"%> 
</p>
<p>
	<%= f.text_field :email_sender ,  :class=>"txt_small" %>
	<span class="hint_1"> Email will be sent from this address</span>
</p>

<p>
	<%= f.label :email_subject %>
</p>
<p>
	<%= f.text_field :email_subject ,  :class=>"txt_small" %>
	<span class="hint_1">Subject line of the email that will be sent to users</span>
</p>

<p>
	<%= f.label :welcome_email , "Email body"%>
</p>
<p>
	<%= f.text_area :welcome_email ,  :class=>"txt_small" %>
	<span class="hint_1"> Email content that will be sent to users</span>
</p>

app/views/sites/_tabs_7.html.erb
<p>
	<%= f.label :name_color %>
</p>
<p>
	<%= f.text_field :name_color,  :class=>"txt_small" %>
	<span class="hint_1">Will appear at the top of your site (unless you upload a logo) </span>
</p>
<p>
	<%= f.label :tagline_color %>
</p>
<p>
	<%= f.text_field :tagline_color,  :class=>"txt_small" %>
	<span class="hint_1">Will appear at the top of your site (unless you upload a logo) </span>
</p>
<p>
	<%= f.label :description_color %>
</p>
<p>
	<%= f.text_field :description_color,  :class=>"txt_small" %>
	<span class="hint_1">Will appear at the top of your site (unless you upload a logo) </span>
</p>
<p>
	<%= f.label :box_color , "Box Color" %>
</p>
<p>  
	<%= f.text_field :box_color,  :class=>"txt_small" %>
	<span class="hint_1"> What color you want as background for site block?</span>
</p>
<div class="site_description_color" style="display:none"></div>
<div class="site_tagline_color" style="display:none"></div>
<div class="site_name_color" style="display:none"></div>
<div class="site_box_color" style="display:none"></div>
<%= hidden_field_tag 'tab', '' %>		

app/views/sites/edit.html.erb
<%= render 'form' %>


<script type="text/javascript">
	$(function(){
		$('.footwrap').css({'position':'relative','top':'0px'});
	});
</script>

app/views/sites/view.html.erb
<%= render 'view' %>