config/routes.rb
LaunchGator::Application.routes.draw do

  resources :contact_us,:only=>[:new,:create]

  match '/:id' => 'invites#referral', :constraints => {:id => /[a-zA-Z]{3}[0-9]{3}/}

  resources :invites,:only=>[:create] do
    member do
      get 'referral'
    end
  end

  resources :sites, :only=>[:index,:edit,:update]   do
    member do
      get 'view'
    end
    resources :invites,:only=>[:index]
  end

  devise_for :users, controllers: { omniauth_callbacks: "sessions" }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users, :only => [:index] do
    collection do
      get 'home'
    end

  end

  post 'check_user' => 'users#check_user', :as => :check_user
  get 'terms'=>'pages#terms',:as=>:terms
  get 'contact' => 'contact_us#new',:as=>:contact
  get 'about' => 'pages#about', :as => :about
  get 'terms'=>'pages#terms',:as=>:terms
  get 'privacy_policy'=>'pages#privacy_policy',:as=>:privacy_policy

  get 'check_domain_propagated' => 'sites#check_domain_propagated', :as=> :check_domain_propagated
  match 'auth/failure', to: redirect('/')

  root :to => 'users#home'

  constraints(Subdomain) do
    root :to => 'sites#view'
  end

end

app/views/layouts/_analytics_codes.html.erb
<!-- Google Analytics Starts-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= @site.google_analytics_code  if @site.google_analytics_code.present?%>');
  ga('send', 'pageview');

</script>
 <!-- Google Analytics Ends-->

app/views/layouts/_facebook_meta_tags.html.erb
<% if params[:controller]=="users" and params[:action]=="home" %>

	<meta property="fb:app_id" content="221146287988508"/>
	<meta property="og:site_name" content="LaunchGator"/>
	<meta property="og:type" content="Article"/>
	<meta property="og:url" content="<%=  %>"/>
	<meta property="og:title"  content="<%= 'LauchGator - Create a launching soon viral page in minutes for free.' %>"/>
	<meta property="og:description" content="<%= 'Create a simple and easy to use viral page for your new product launches. Collect emails and allow people to spread the word about your product for free. ' %>"/>
	<meta property="og:image" content='http://launch.deskgator.com/image/logo_facebook.png'/>

<% end %>

app/views/layouts/_features.html.erb
<!--Features Section-->
<div class="features">		
	<h1>THINGS YOU CAN DO WITH LAUNCH GATOR</h1>
	<!-- Left Img Container -->
	<div class="highlight">
		<%= image_tag "/assets/create.png", alt:"Create a page" %>
		<div class="highlight_content">
			<h1>Create &amp; Customize</h1>
			<p>Create awesome coming soon pages for your upcoming website. Log In and add your website information. Add custom colors and backgrounds that highlight your service.</p>
		</div>
	</div>
	<!-- Left Img Container Ends-->
	<!-- Left Img Container -->
	<div class="highlight">
		<div class="highlight_content">
			<h1>Share &amp; Engage</h1>
			<p>Share your landing page with your friends via social networks or emails and spread the word. Gather valuable feedback and bring your website to limelight.</p>
		</div>
		<%= image_tag "/assets/share.png", alt:"Share page" %>
	</div>
	<!-- Left Img Container Ends-->
	<!-- Right Img Container -->
	<div class="highlight">
		<%= image_tag "/assets/connect.png", alt:"Connect" %>
		<div class="highlight_content">
			<h1>Understand &amp; Connect</h1>
			<p>Understand the kind of audience that is visiting your landing page and connect with them to share and exchange valuable ideas that can be fruitful for your actual website.</p>
		</div>
	</div>
	<!-- Right Img Container Ends-->
</div>
			<!--Features Section-->

app/views/layouts/_footer.html.erb
<!-- Footer Wrapper -->
   	<div class="footwrap">
    	<!-- Footer Content -->
    	<div class="footer">
            <div class="footnav">
                <h1>Launch Gator</h1>
                <ul>
                    <li><%= link_to 'Home', root_path %></li>
                      <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Contact Us", contact_path %></li>
                    <br class="clearfix"/>
                </ul>
            </div>
            <div class="footnav">
                <h1>Links</h1>
                <ul>
                      <li><%= link_to "Privacy", privacy_policy_path %></li>
                    <li><%= link_to "Terms", terms_path %></li>
                    <br class="clearfix"/>
                </ul>
            </div>
            <div class="footnav">
            	<h1>Related</h1>
                <ul>
					<li><%= link_to "NaviGator", 'http://navi.deskgator.com',:target=>'_blank' %></li>
                	<li><%= link_to "SocialGator", 'http://social.deskgator.com',:target=>'_blank' %></li>
					<li><%= link_to "EmailGator", 'http://email.deskgator.com',:target=>'_blank' %></li>
                    <br class="clearfix"/>
                </ul>
            </div>
            <div class="footnav">
            	<h1>Social</h1>
                <ul>
                	<li><a href="http://www.facebook.com/pages/Fizzy-Software/182961565160614" target="_blank">Facebook</a></li>
                    <li><a href="http://twitter.com/fizzysoftware" target="_blank">Twitter</a></li>
                    <li><a href="http://www.linkedin.com/company/2149207" target="_blank">LinkedIn</a></li>                   <br class="clearfix"/>
                </ul>
            </div>
	            	<div class="company">
	            	<a href="http://www.fizzysoftware.com" target="_blank"><img src="/assets/fizzy.png" alt="A Product of Fizzy Software"></a>
                    <p>Copyright &copy; <%= Time.now.strftime("20%y")%>,&nbsp;<%= link_to "Fizzy Software", "http://fizzysoftware.com",:target=>'_blank'%></p>
	            </div>

            <!-- Footer Content Ends -->
    </div>

    <!-- Footer Wrapper Ends -->

app/views/layouts/_header.html.erb
<% if @site.id == 1 || (@site.id != 1 && (params[:controller]=="sites" || params[:controller]=="invites" )) %>
<!-- Head Wrapper -->
<div class="headwrap" id="home">
	<!-- Head Content -->
	<div class="head">
		<% if session[:user_id].nil? %>
			<%= link_to (image_tag "logo.png",  :class=>'logo' ) , root_path%>
		<% elsif !@site.new_record? %>
			<%= link_to (image_tag "logo.png",  :class=>'logo' ) , edit_site_path(@site) %>
		<% else %>
			<%= link_to (image_tag "logo.png",  :class=>'logo' ) , new_site_path %>
		<% end %>

		<% if user_signed_in? %>
			<div class="line">
				<div class="fline" style="<%= (@site.state == 0 or @site.state == 1) ? 'width:0%' : @site.state == 2 ? 'width:50%' : 'width:100%'%>"></div>
				<span class="cpoint pone <%= 'reached' if @site.state != 0 %>" data-info="Fill basic requirements to launch of the landing page"></span>
				<span class="cpoint ptwo <%= 'reached' if @site.state.between?(2,3) %>" data-info="Change background images and logo of the page etc."></span>
				<span class="cpoint pthree <%= 'reached' if @site.state == 3 %>" data-info="Point the cname records of your desired domain to host.deskgator.com"></span>
			</div>
		<% end %>

		<!-- Main Navigation -->
		<ul class="mainnav">
			<% if !user_signed_in? %>
				<li><%= link_to "Log In", new_user_session_path %></li>
				<li><%= link_to "Sign Up", new_user_registration_path,:class => "signupbtn" %></li>
			<% else %>
				<li>
					<%= link_to "Your Page", edit_site_path(@site) ,:class => active_class(params[:action],'edit') %>
				</li>
				<li>
					<%= link_to "Insights", site_invites_path(@site) ,:class => active_class(params[:action],'index')%>
				</li>
				<li>
					<%= link_to "Logout", destroy_user_session_path, method: :delete %>
				</li>
			<% end %>
		</ul>
		<!-- Main Navigation Ends-->
	</div>
	<!-- <div class ="fork">
		<%= link_to image_tag('fork.png'), 'https://github.com/fizzysoftware/LaunchGator',:target => '_blank' %>
	</div> -->
	<!-- Head Content Ends -->
</div>
<!-- Head Wrapper Ends-->
<% end %>

app/views/layouts/_javascripts.html.erb
<script>

(function() {

  jQuery(function() {
    $('body').prepend('<div id="fb-root"></div>');
    return $.ajax({
      url: "" + window.location.protocol + "//connect.facebook.net/en_US/all.js",
      dataType: 'script',
      cache: true
    });
  });
  window.fbAsyncInit = function() {
    FB.init({
      appId: '<%= ENV["FACEBOOK_KEY"] %>',
      cookie: true
    });
    $('#facebook_sign_in').click(function(e) {
      e.preventDefault();
      return FB.login(function(response) {
        if (response.authResponse) {
          return window.location = '/users/auth/facebook';
        }
      }, {
        scope: "email"
      });
    });
    return $('#sign_out').click(function(e) {
      FB.getLoginStatus(function(response) {
        if (response.authResponse) {
          return FB.logout();
        }
      });
      return true;
    });
  };

}).call(this);
</script>

app/views/layouts/_service_codes.html.erb
<% if Rails.env.production? %>

  <!-- Start of Interakt Script -->

  <% if current_user %>
    <%# Interakt script %>
    <script>
      window.mySettings = {
      // TODO: The current logged in user's email address.
      email: '<%= current_user.email %>',
      name: '<%= current_user.full_name %>',
      sign_in_count: '<%= current_user.sign_in_count %>',
      site_name: '<%= current_user.site.name %>',
      site_url: '<%= current_user.site.url %>',
      cname_checked: '<%= current_user.site.domain_propagated %>',
      last_sign_in_at: '<%= current_user.last_sign_in_at %>',
      last_sign_in_ip: '<%= current_user.last_sign_in_ip %>',
      // TODO: The current logged in user's sign-up date.
      created_at: '<%= current_user.created_at %>',
      app_id: 'interakt_app_id'
      // Sending Custom Hash with unique_id
      };
    </script>
  <% end %>

    <script>
      (function() {
      var interakt = document.createElement('script');
      interakt.type = 'text/javascript'; interakt.async = true;
      interakt.src = "https://interakt.co/interakt/interakt_app_id.js"
      var scrpt = document.getElementsByTagName('script')[0];
      scrpt.parentNode.insertBefore(interakt, scrpt);
      })()
    </script>

<% end %>

<!-- Google Analytics Starts-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'RANDOM-888999777-11']);
  _gaq.push(['_setDomainName', 'yourdomain.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- Google Analytics Ends-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
		<title><%= @title %></title>
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
		<![endif]-->
		<link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico">
		<link href='//fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/facebook_meta_tags' if @site.id == 1 %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<script type="text/javascript">
			$(document).ready(function(){
				$("body").ezBgResize({
					img : "<%= @background_image %>", // Required.
				});
			});
		</script>
		<script type="text/javascript">
			$(function(){
				var bodyheight = $(window).height();
				$('.launchbody').css({'min-height': bodyheight });
				$('.features').delay(5000).fadeIn(200);
				$('#notice').delay(3000).slideUp(200);
				$('#error').delay(3000).slideUp(200);
			});
		</script>


		<% if (params[:controller] == "users" and params[:action] == "home" and @site.id != 1) %>
		<% if (@site.image.present? and @site.image.id.present? and @site.image.logo.present?) %>
		<meta property="og:image" content="<%= @site.image.logo.url(:medium) %>"/>
		<% end %>
		<meta property="og:description" content="<%= @site.description if @site.description.present? %>"/>
		<meta property="og:title" content="<%= @site.tagline if @site.tagline.present? %>"/>
		<% end  %>

	</head>
	<body>

		<!-- Kiss Insights Starts-->
		<!--  <%# if params[:controller] == "users" and params[:action] == "home" and @site.id == 1 %>
			<script type="text/javascript">var _kiq = _kiq || [];</script>
			<script type="text/javascript" src="//s3.amazonaws.com/ki.js/22616/8OJ.js" async="true"></script>
		<%# end %>
	-->
	<!-- Kiss Insights Starts-->

	<%= render "layouts/header" %>

	<div class="launchbody">
		<% if params[:controller] == "users" && params[:action] == "home" && @site.id.to_i != 1 %>
		<div id="wrapper" class="<%= @site.box_alignment %>" style="background-color:<%= @site.box_color %>!important">
			<% elsif (params[:controller] == "invites" ||params[:controller] == "sites" || params[:controller] == "users") and params[:action] == "index" %>
			<div id="wrapper" class="sites_invite">
				<% elsif params[:controller] == "sites" and (params[:action] == "edit" || params[:action] == 'update') %>
				<div>
					<% else %>
					<div id="wrapper" >
						<% end %>
						<% if flash[:notice] %>
						<div id='notice'><%= flash[:notice].html_safe %></div>
						<% end %>

						<% if flash[:error] %>
						<div id='error'><%= flash[:error].html_safe %></div>
						<% end %>

						<%= yield %>
					</div>

					<% if params[:controller] == "users" and params[:action] == "home" and @site.id == 1 %>
					<%= render "layouts/features" %>
					<% end %>
				</div>

				<script>
					$(function(){
						$( "#site_wrapper , #site_builder").draggable();

					});
				</script>

				<% if (@site.id == 1 || (params[:action] != 'home' and @site.id == 1 )) && (@site.id == 1 && params[:action] != 'edit') %>

				<%= render "layouts/footer" %>

				<% end %>
				<%= render "layouts/analytics_codes" if (params[:controller] == "users" and params[:action] == "home" and @site.id != 1) %>
				<%= render "layouts/service_codes" if !(params[:controller] == "users" and params[:action] == "home" and @site.id != 1) %>
			</body>
			</html>